//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmonikItog
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionTime
    {
        public int Session_timeId { get; set; }
        public int Id { get; set; }
        public System.DateTime Date_login { get; set; }
        public System.TimeSpan Login_time { get; set; }
        public Nullable<System.TimeSpan> Logout_time { get; set; }
        public Nullable<System.TimeSpan> Time_spent { get; set; }
        public string Unsuccessful_logout { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
