//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmonikItog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.SessionTime = new HashSet<SessionTime>();
        }
    
        public int Id { get; set; }
        public string Role_user { get; set; }
        public string Email { get; set; }
        public string Password_p { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public System.DateTime Birthdate { get; set; }
        public bool Active { get; set; }
        public bool Chek { get; set; }
    
        public virtual ICollection<SessionTime> SessionTime { get; set; }
    }
}
