//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class newHotelEntities : DbContext
    {
        private static newHotelEntities _context;
        public newHotelEntities()
            : base("name=newHotelEntities")
        {
        }

        public static newHotelEntities GetContext()
        {
            if (_context == null)
                _context = new newHotelEntities();
            return _context;
        }



        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<HotellImage> HotellImage { get; set; }
        public virtual DbSet<ImageTour> ImageTour { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Type_Hotel> Type_Hotel { get; set; }
    }
}
