//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmonikPop2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Runtime.Remoting.Contexts;

   
    public partial class Session1_01_BerezkaEntities : DbContext
    {
        private static Session1_01_BerezkaEntities _context;
        public Session1_01_BerezkaEntities()
            : base("name=Session1_01_BerezkaEntities")
        {
        }

        public static Session1_01_BerezkaEntities GetContext()
        {
            if (_context == null)
                _context = new Session1_01_BerezkaEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SessionTime> SessionTime { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
